#!/bin/bash
find . -type f -empty -exec sh -c 'printf "%s\n" "${@##*/}"' _ {} + -o -type d -empty -exec sh -c 'printf "%s\n" "${@##*/}"' _ {} + -o -type f -name ".*" -empty -exec sh -c 'printf "%s\n" "${@##*/}"' _ {} + -o -type d -name ".*" -empty -exec sh -c 'printf "%s\n" "${@##*/}"' _ {} +
