#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data

log_file="apache-access.log"

# Check if the log file exists and is not empty
if [ -s "$log_file" ]; then
    # Check if the log file has the correct format
    if awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' "$log_file" 2>/dev/null; then
        # Display the grouped visitors by IP and HTTP status code
        awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' "$log_file" | sort -nr | awk '{$1=$1;print}'
    else
        echo "Error: Wrong format log file"
    fi
else
    if [ ! -f "$log_file" ]; then
        echo "Error: Log file not found"
    elif [ -s "$log_file" ]; then
        echo "Error: Log file is empty"
    fi
fi
