#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Print the header
echo "USER       START COMMAND"

# Use ps command to list all processes
ps -eo user,start_time,cmd | sort -k 1,1 -k 2,2n
