#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Print the header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Use ps command to list all processes
ps -eo user,pid,%cpu,%mem,vsize,rss,tty,stat,start,time,cmd | sort -k 1,1 -k 2,2n
